language: python
python: "3.7"
os: linux
dist: xenial
services: docker
install: 
  - pip install -r requirements.txt
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
  - unzip /tmp/awscliv2.zip -d /tmp/
  - sudo sh /tmp/aws/install
script: 
  - set -e
  - python manage.py test
  - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${REPOSITORY_URI}
  - docker build . -t confessions:${TRAVIS_BUILD_NUMBER}
  - docker push docker push ${REPOSITORY_URI}/confessions:${TRAVIS_BUILD_NUMBER}
before_deploy:
  - wget https://releases.hashicorp.com/terraform/0.12.26/terraform_0.12.26_linux_amd64.zip -O /tmp/terraform.zip
  - sudo unzip /tmp/terraform.zip -d /usr/local/bin
  - export TF_PLUGIN_CACHE_DIR="$HOME/.terraform.d/plugin-cache"
  - export TF_VAR_IMAGE_VERSION=${TRAVIS_BUILD_NUMBER}
  - export TF_VAR_REPOSITORY_URI=${REPOSITORY_URI}
deploy:
  provider: script
  script: 
    - cd infra && apply-all
  on branch: master
